### ISSUE TITLE
permission to link your theme?

### ISSUE THREAD

**Issue by lixxbox** [steadyjaw/dracula-mainsail-theme#1]
hi, 
I am currently reworking parts of the [mainsail docs](https://docs.mainsail.xyz).
If it is okay for you, I would like to link your dracula theme in a new "themes" page, of course with credits and a small preview.

I would be pleased if you would give me your permission.

**Comment by dw-0** [comment]
I just join that request but don't want to open a second issue for that.
Im thinking about an installer for that theme in KIAUH if you don't mind so people using that tool can install it through KIAUH if they want. ( https://github.com/th33xitus/kiauh ) 

Are you okay with that?

**Comment by steadyjaw** [comment]
Hey guys.
sure, of course! please. :)

**Comment by steadyjaw** [comment]
Permission granted.
